### ISSUE TITLE
ESL-Files einlesen

### ISSUE THREAD

**Issue by zwazel** [BZZ-2020/M306B#2]
- [ ] Cache
- [ ] ....

**Comment by xXZAWARUDOXx** [comment]
- Check how to get an attribute from an XML-Header
- parseFile() --> with methods for building the values with Builder class (lombok)
- getFileDate --> TimePeriodEnd must, created --> from Header nice-to-have

**Comment by zwazel** [comment]
- [x] Mehrere Tage in einem File werden nicht gehandelt
- [x] z.b "EdmRegisterWertExport_20190731_eslevu_20190726150757.xml" hat nicht alle daten, was passiert damit?
